version: '3.8'

services:

  postgres:
    image: postgres:17.7
    container_name: postgres_vendas_dev
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: mongodb_dev
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo_dev_data:/data/db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_gui_dev
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "5050:80"

  api:
    build: .
    container_name: vendas_api_dev
    restart: always
    depends_on:
      - postgres
      - mongo
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      JWT_SECRET: ${JWT_SECRET}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      MONGO_URI: ${MONGO_URI}

volumes:
  postgres_data_dev:
  mongo_dev_data:
